<script lang="ts">
	// The BumpyScore details view (shown in a modal): the score on its 0–100 scale,
	// what the number means, the AI's read, and the day's disclaimers.
	import Moon from '@lucide/svelte/icons/moon';
	import AiNote from '$lib/AiNote.svelte';
	import type { BumpyAnalysis, Vessel } from '$lib/jeby/models';
	import { SCORE_BAR_GRADIENT, scoreColor, scoreLabel } from '$lib/jeby/score';

	let {
		score,
		disclaimers,
		analysis,
		vessel,
		quietHours = false
	}: {
		score: number | null;
		disclaimers: string[];
		analysis: BumpyAnalysis | null;
		vessel: Vessel | null;
		quietHours?: boolean;
	} = $props();

	const markerColor = $derived(score == null ? '#ffffff' : scoreColor(score));
	const TICKS = [0, 25, 50, 75, 100];
</script>

<div class="space-y-6">
	<!-- Score + where it sits on the scale -->
	<div>
		<div class="flex items-baseline gap-2">
			{#if quietHours}
				<Moon size={44} class="text-neutral-400" />
			{:else}
				<span class="text-6xl font-semibold leading-none tracking-tighter text-white">
					{score ?? '—'}
				</span>
				<span class="text-base font-medium text-neutral-500">/ 100</span>
			{/if}
			{#if score != null}
				<span class="ml-auto text-sm font-medium" style="color: {markerColor}">
					{scoreLabel(score)}
				</span>
			{/if}
		</div>

		{#if vessel}
			<p class="mt-2 text-sm text-neutral-400">Calibrated for the {vessel.name}.</p>
		{/if}

		<!-- The scale the score sits on -->
		<div class="mt-5">
			<div class="relative h-2.5 w-full rounded-full" style="background: {SCORE_BAR_GRADIENT}">
				{#if score != null}
					<div
						class="absolute top-1/2 h-5 w-5 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 bg-white shadow"
						style="left: {Math.min(100, Math.max(0, score))}%; border-color: {markerColor}"
					></div>
				{/if}
			</div>
			<div class="mt-2 flex justify-between text-xs text-neutral-500">
				{#each TICKS as tick (tick)}
					<span>{tick}</span>
				{/each}
			</div>
			<div class="mt-1 flex justify-between text-xs text-neutral-500">
				<span>Glassy calm</span>
				<span>Dangerous</span>
			</div>
		</div>
	</div>

	<!-- Why the score came out where it did -->
	<div class="border-t border-border pt-5">
		<AiNote text={analysis?.bumpy ?? null} />
	</div>

	<!-- Today's disclaimers -->
	{#if disclaimers.length}
		<div class="border-t border-border pt-5">
			<h4 class="text-xs font-semibold uppercase tracking-wide text-neutral-400">
				Today's disclaimers
			</h4>
			<ul class="mt-2 list-disc space-y-2 pl-5 text-sm leading-relaxed text-neutral-300">
				{#each disclaimers as d (d)}
					<li>{d}</li>
				{/each}
			</ul>
		</div>
	{/if}

	<p class="border-t border-border pt-5 text-xs leading-relaxed text-neutral-500">
		The BumpyScore&trade; is an estimate generated by AI from live station readings and your
		vessel's specs. AI can make mistakes. The captain of the vessel is solely responsible for its
		safe operation and for all decisions made aboard.
	</p>
</div>
